proxy_cache_path /var/cache/nginx/report-cache levels=1:2 keys_zone=report_cache:10m max_size=256m inactive=30m use_temp_path=off;

server {
    listen 80;
    server_name _;

    location /reports-cache/ {
        rewrite ^/reports-cache/(.*)$ /bionicpro-reports/$1 break;

        proxy_pass http://minio:9000;
        proxy_set_header Host minio:9000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache report_cache;
        proxy_cache_valid 200 5m;
        proxy_cache_valid 404 30s;
        proxy_cache_lock on;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        add_header X-Report-Cache-Status $upstream_cache_status always;
    }
}
