services:
  keycloak_db:
    image: postgres:18.4
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql
    ports:
      - "5433:5432"
  keycloak:
    image: keycloak/keycloak:nightly
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
  bionicpro-auth:
    build:
      context: ./bionicpro-auth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      FRONTEND_URL: http://localhost:3000
      KEYCLOAK_AUTH_SERVER_URL: http://localhost:8080
      KEYCLOAK_INTERNAL_AUTH_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: reports-realm
      KEYCLOAK_CLIENT_ID: bionicpro-auth
      KEYCLOAK_CLIENT_SECRET: bionicpro-auth-secret
      KEYCLOAK_REDIRECT_URI: http://localhost:8000/auth/callback
      SESSION_TTL: 30m
      SESSION_SECURE_COOKIE: "true"
    depends_on:
      - keycloak
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
